### ISSUE TITLE
app crashes after re-entering VS Code menu item

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#142]
The app crashed after re-entering vscode menu item. This appeared on release image 0.15.3 lite. 

```py
1720846020.109851 [ERROR] An error occurred while running the app.
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/main.py", line 56, in main
    app.run()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/app.py", line 956, in run
    runTouchApp()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 339, in mainloop
    self.idle()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 379, in idle
    Clock.tick()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/clock.py", line 776, in post_idle
    self._process_events()
  File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/store/main.py", line 70, in <lambda>
    trigger = Clock.create_trigger(lambda _: callback(), 0, interval=interval)
                                             ^^^^^^^^^^
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/main.py", line 160, in run
    self._run_actions()
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/main.py", line 139, in _run_actions
    self._call_listeners(self._state)
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/main.py", line 128, in _call_listeners
    result = listener(state)
             ^^^^^^^^^^^^^^^
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/autorun.py", line 83, in <lambda>
    lambda state: self._call()
                  ^^^^^^^^^^^^
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/autorun.py", line 203, in _call
    self.inform_subscribers()
  File "/opt/ubo/env/lib/python3.11/site-packages/redux/autorun.py", line 114, in inform_subscribers
    subscriber(self._latest_value)
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_gui/menu/__init__.py", line 218, in handle_menu_change
    last_item = self._replace(last_item, menu)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_gui/menu/__init__.py", line 627, in _replace
    raise ValueError(msg) from None
ValueError: `stack_item` not found in stack
```

**Comment by sassanh** [comment]
It is fixed in 0.15.4.
