### ISSUE TITLE
Second phase of update process must be able to run completely offline

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#178]
In version 0.17.2 if the pod has no Internet connection during the 2nd phase of update, the `ubo-update.service` fails and the device becomes unresponsive. This is due to the fact that service tries to access some online services which are not needed.

Below is an example of such failure:

```sh
Oct 05 19:54:48 ubo-h2 install.sh[1546]: sudo: unable to resolve host ubo-h2: Temporary failure in name resolution
Oct 05 19:54:48 ubo-h2 sudo[1546]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/gpg --dearmor -o /etc/apt/keyrings/docker.gpg
Oct 05 19:54:48 ubo-h2 sudo[1546]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Oct 05 19:54:48 ubo-h2 install.sh[1545]: curl: (6) Could not resolve host: download.docker.com
Oct 05 19:54:48 ubo-h2 install.sh[1547]: gpg: no valid OpenPGP data found.
Oct 05 19:54:48 ubo-h2 sudo[1546]: pam_unix(sudo:session): session closed for user root
Oct 05 19:54:48 ubo-h2 install.sh[1329]: Failed to install docker, giving up!
Oct 05 19:54:48 ubo-h2 install.sh[1329]: Done installing docker
Oct 05 19:54:48 ubo-h2 install.sh[1329]: Installing wm8960...
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + set -o errexit
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + set -o pipefail
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + set -o nounset
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + [[ 0 -ne 0 ]]
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + '[' '!' -f /etc/rpi-issue ']'
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + rm -rf WM8960-Audio-HAT
Oct 05 19:54:48 ubo-h2 install.sh[1549]: + git clone https://github.com/waveshare/WM8960-Audio-HAT
Oct 05 19:54:48 ubo-h2 install.sh[1551]: Cloning into 'WM8960-Audio-HAT'...
Oct 05 19:54:48 ubo-h2 install.sh[1553]: fatal: unable to access 'https://github.com/waveshare/WM8960-Audio-HAT/': Could not resolve host: github.com
Oct 05 19:54:48 ubo-h2 install.sh[1329]: Traceback (most recent call last):
Oct 05 19:54:48 ubo-h2 install.sh[1329]:   File "/opt/ubo/env/bin/bootstrap", line 8, in <module>
Oct 05 19:54:48 ubo-h2 install.sh[1329]:     sys.exit(main())
Oct 05 19:54:48 ubo-h2 install.sh[1329]:              ^^^^^^
Oct 05 19:54:48 ubo-h2 install.sh[1329]:   File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/bootstrap.py", line 10, in main
Oct 05 19:54:48 ubo-h2 install.sh[1329]:     bootstrap(
Oct 05 19:54:48 ubo-h2 install.sh[1329]:   File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/system/bootstrap.py", line 277, in bootstrap
Oct 05 19:54:48 ubo-h2 install.sh[1329]:     install_audio_driver(in_packer=in_packer)
Oct 05 19:54:48 ubo-h2 install.sh[1329]:   File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/system/bootstrap.py", line 221, in install_audio_driver
Oct 05 19:54:48 ubo-h2 install.sh[1329]:     subprocess.run(  # noqa: S603
Oct 05 19:54:48 ubo-h2 install.sh[1329]:   File "/usr/lib/python3.11/subprocess.py", line 571, in run
Oct 05 19:54:48 ubo-h2 install.sh[1329]:     raise CalledProcessError(retcode, process.args,
Oct 05 19:54:48 ubo-h2 install.sh[1329]: subprocess.CalledProcessError: Command '['/opt/ubo/env/lib/python3.11/site-packages/ubo_app/system/install_wm8960.sh', '--in-packer']' returned non-zero exit stat>
Oct 05 19:54:48 ubo-h2 systemd[1]: ubo-update.service: Main process exited, code=exited, status=1/FAILURE
Oct 05 19:54:48 ubo-h2 systemd[1]: ubo-update.service: Failed with result 'exit-code'.
Oct 05 19:54:48 ubo-h2 systemd[1]: ubo-update.service: Consumed 1min 11.877s CPU time.
Oct 05 19:55:33 ubo-h2 kernel: Console: switching to colour frame buffer device 240x67
Oct 05 19:55:33 ubo-h2 kernel: vc4-drm gpu: [drm] fb0: vc4drmfb frame buffer device
```

**Comment by mehrdadfeller** [comment]
@sassanh Can I test this on v1.0.0? I believe you have addressed it already but not sure if it is on v1.0.0 or later dev versions.

**Comment by sassanh** [comment]
@mehrdadfeller No, I haven't worked on it yet.
