### ISSUE TITLE
permission denied error when deleting a WiFi network

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#183]
I cannot delete a WiFi network on software `v1.0`. I see the following errors in the logs.

I got this also on [sentry](https://ubo-technology-llc.sentry.io/issues/5986086759/?alert_rule_id=15083781&alert_timestamp=1728701422693&alert_type=email&environment=production&notification_uuid=7e735d8f-14d5-4cfc-a874-f4f6073e51d4&project=4506981135876096&referrer=alert_email).

```sh
1728702093.742532 [ERROR] Event loop exception
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/030-wifi/wifi_manager.py", line 379, in forget_wireless_connection
    await wait_for(network_connection_settings.delete())
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/opt/ubo/env/lib/python3.11/site-packages/sdbus/dbus_proxy_async_method.py", line 107, in _dbus_async_call
    reply_message = await bus.call_async(call_message)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sdbus_async.networkmanager.exceptions.NmSettingsPermissionDeniedError: Insufficient privileges - extra: {
  "error_message": "Task exception was never retrieved",
  "future": "<Task finished name='Task-17565' coro=<forget_wireless_connection() done, defined at /opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/030-wifi/wifi_manager.py:362> exception=NmSettingsPermissionDeniedError('Insufficient privileges')>",
  "loop": "<_UnixSelectorEventLoop running=True closed=False debug=False>",
  "parent_stack": "None"
}
```

**Comment by zytegalaxy** [comment]
@sassanh I suggest we try to find a temporary solution that allows us to keep ubo as sudoer and address permission issue with polkit settings; later we should separate login and deskop users and let the pod owner give a user sudo access via GUI as discussed: https://github.com/orgs/ubopod/projects/1/views/1?pane=issue&itemId=83704218&issue=ubopod%7Cubo_app%7C184
