### ISSUE TITLE
No audio card found errors in bear bone operations 

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#197]
I was testing the software (v1.0.0) with no audio hardware available and I see lots of `No audio card found` errors being reported. This will wear out the MicroSD card and fill up the storage overtime. 

```
StopIteration
1733200208.513170 [ERROR] No audio card found
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-audio/audio_manager.py", line 47, in initialize_audio
    next(card for card in cards if 'wm8960' in card),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
1733200208.533263 [ERROR] No audio card found
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-audio/audio_manager.py", line 47, in initialize_audio
    next(card for card in cards if 'wm8960' in card),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
1733200208.553574 [ERROR] No audio card found
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-audio/audio_manager.py", line 47, in initialize_audio
    next(card for card in cards if 'wm8960' in card),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
1733200208.573448 [ERROR] No audio card found
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-audio/audio_manager.py", line 47, in initialize_audio
    next(card for card in cards if 'wm8960' in card),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
1733200208.593369 [ERROR] No audio card found
Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/services/000-audio/audio_manager.py", line 47, in initialize_audio
    next(card for card in cards if 'wm8960' in card),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mehrdadfeller** [comment]
this issue has been fixed
