### ISSUE TITLE
App crashed v1.0.0 when I pressed back on RPi Connect View

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#199]
Not sure what caused this but seems like a low level kivy error...

```python
1734851015.646057 [ERROR] An error occurred while running the app.
Traceback (most recent call last):
  File "kivy/core/window/_window_sdl2.pyx", line 28, in kivy.core.window._window_sdl2._event_filter
  File "kivy/core/window/_window_sdl2.pyx", line 28, in kivy.core.window._window_sdl2._event_filter
  File "kivy/core/window/_window_sdl2.pyx", line 28, in kivy.core.window._window_sdl2._event_filter
  [Previous line repeated 1 more time]
  File "kivy/core/window/_window_sdl2.pyx", line 58, in kivy.core.window._window_sdl2._WindowSDL2Storage.cb_event_filter
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/core/window/window_sdl2.py", line 280, in _event_filter
    EventLoop.idle()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 400, in idle
    window.dispatch('on_draw')
  File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/core/window/__init__.py", line 1676, in on_draw
    self.render_context.draw()
  File "kivy/graphics/instructions.pyx", line 640, in kivy.graphics.instructions.Canvas.draw
  File "kivy/graphics/instructions.pyx", line 643, in kivy.graphics.instructions.Canvas.draw
  File "kivy/graphics/instructions.pyx", line 917, in kivy.graphics.instructions.RenderContext.apply
  File "kivy/graphics/instructions.pyx", line 654, in kivy.graphics.instructions.Canvas.apply
  File "kivy/graphics/instructions.pyx", line 167, in kivy.graphics.instructions.InstructionGroup.apply
  File "kivy/graphics/instructions.pyx", line 181, in kivy.graphics.instructions.InstructionGroup.build
  File "kivy/graphics/compiler.pyx", line 143, in kivy.graphics.compiler.GraphicsCompiler.compile
  File "kivy/graphics/instructions.pyx", line 654, in kivy.graphics.instructions.Canvas.apply
  File "kivy/graphics/instructions.pyx", line 167, in kivy.graphics.instructions.InstructionGroup.apply
  File "kivy/graphics/instructions.pyx", line 181, in kivy.graphics.instructions.InstructionGroup.build
  File "kivy/graphics/compiler.pyx", line 143, in kivy.graphics.compiler.GraphicsCompiler.compile
  File "kivy/graphics/instructions.pyx", line 654, in kivy.graphics.instructions.Canvas.apply
  File "kivy/graphics/instructions.pyx", line 167, in kivy.graphics.instructions.InstructionGroup.apply
  File "kivy/graphics/instructions.pyx", line 181, in kivy.graphics.instructions.InstructionGroup.build
  File "kivy/graphics/compiler.pyx", line 143, in kivy.graphics.compiler.GraphicsCompiler.compile
  File "kivy/graphics/fbo.pyx", line 390, in kivy.graphics.fbo.Fbo.apply
  File "kivy/graphics/instructions.pyx", line 917, in kivy.graphics.instructions.RenderContext.apply
  File "kivy/graphics/instructions.pyx", line 654, in kivy.graphics.instructions.Canvas.apply
  File "kivy/graphics/instructions.pyx", line 167, in kivy.graphics.instructions.InstructionGroup.apply
  File "kivy/graphics/instructions.pyx", line 181, in kivy.graphics.instructions.InstructionGroup.build
  File "kivy/graphics/compiler.pyx", line 143, in kivy.graphics.compiler.GraphicsCompiler.compile
  File "kivy/graphics/instructions.pyx", line 173, in kivy.graphics.instructions.InstructionGroup.apply
  File "kivy/graphics/instructions.pyx", line 506, in kivy.graphics.instructions.Callback.apply
  File "/opt/ubo/env/lib/python3.11/site-packages/headless_kivy/widget.py", line 171, in process_frame
    mask = np.any(data != self.previous_frame, axis=2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in any
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2423, in any
    return _wrapreduction(a, np.logical_or, 'any', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.AxisError: axis 2 is out of bounds for array of dimension 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ubo/env/lib/python3.11/site-packages/ubo_app/main.py", line 84, in main
    app.run()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/app.py", line 956, in run
    runTouchApp()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/base.py", line 341, in mainloop
    self.window.mainloop()
  File "/opt/ubo/env/lib/python3.11/site-packages/kivy/core/window/window_sdl2.py", line 574, in mainloop
    event = self._win.poll()
            ^^^^^^^^^^^^^^^^
SystemError: <cyfunction _WindowSDL2Storage.poll at 0x7fff752628e0> returned a result with an exception set
```

**Comment by mehrdadfeller** [comment]
fixed
